name = "moonwalking"
pages_build_output_dir = "frontend/dist"

[durable_objects]
bindings = [
  { name = "HUB", class_name = "Hub", script_name = "mw-hub" }
]

[vars]
# Comma-separated list of symbols to include by default (optional)
VITE_API_URL = "/api"

[[kv_namespaces]]
binding = "WATCHLIST_KV"
id = "562ae453690441bfabbacd0850cbe3c1"
preview_id = "32b5726ad5984b269d508d42fbfd7317"
