name = "moonwalking-worker"
main = "workers/ws.ts"
compatibility_date = "2025-10-02"

[durable_objects]
bindings = [
  { name = "HUB", class_name = "Hub" }
]

[vars]
QUOTE = "USD"
DEBUG = "true"

[[kv_namespaces]]
binding = "SNAPSHOTS_KV"
id = "562ae453690441bfabbacd0850cbe3c1"
preview_id = "32b5726ad5984b269d508d42fbfd7317"

[[migrations]]
tag = "v2"
new_classes = ["Hub"]

[triggers]
crons = ["* * * * *"]

