project_name = "moonwalking"
pages_build_output_dir = "frontend/dist"

[vars]
# Frontend environment variables for build-time (non-secret)
VITE_API_URL = "/api"

[[kv_namespaces]]
binding = "WATCHLIST_KV"
id = "562ae453690441bfabbacd0850cbe3c1"
preview_id = "32b5726ad5984b269d508d42fbfd7317"

[env.preview]
# Add preview-only overrides or bindings here

[env.production]
# Add production-only overrides or bindings here
