name = "moonwalking-worker"
main = "workers/ws.js"
compatibility_date = "2024-08-23"

[durable_objects]
bindings = [
  { name = "HUB", class_name = "Hub" }
]

[vars]
QUOTE = "USD"

[[kv_namespaces]]
binding = "WATCHLIST_KV"
id = "562ae453690441bfabbacd0850cbe3c1"
preview_id = "32b5726ad5984b269d508d42fbfd7317"
